#!/usr/bin/env bash

git reset --hard HEAD
LOCAL=git rev_parse HEAD
REMOTE=git ls-remote https://github.com/Ajinkya-Nawarkar/DCSP_Project.git HEAD

if ["$LOCAL" != "$REMOTE"]
then
    git pull
fi

permit
